apiVersion: placement.kubernetes-fleet.io/v1alpha1
kind: ResourceOverrideSnapshot
metadata:
  name: test-resource-override-snapshot
spec:
  overrideSpec:
    resourceSelectors:
      - group: rbac.authorization.k8s.io
        version: v1
        kind: Role
        name: test-role
    policy:
      overrideRules:
        - jsonPatchOverrides:
            - operator: Add
              path: test-path
              value: test-value
  overrideHash: dGVzdA==